output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "changeme"

filebeat.modules:
  - module: nginx
  - module: mysql
  - module: system
